# Generated by Django 2.1.4 on 2018-12-11 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('artist', models.CharField(blank=True, max_length=30, null=True)),
                ('description', models.CharField(max_length=30)),
                ('release_date', models.DateField(default=django.utils.timezone.now, verbose_name='Realease date')),
                ('album', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=60, null=True)),
                ('music_cover', models.CharField(blank=True, max_length=60, null=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.Categorie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
