# Generated by Django 2.1.3 on 2018-12-09 14:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20181204_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='relase_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
