# Generated by Django 2.1.3 on 2018-12-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_music_relase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='relase_date',
        ),
    ]
