# Generated by Django 2.1.3 on 2018-12-09 15:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_music_relase_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Realease date'),
        ),
    ]
