# Generated by Django 2.1.3 on 2018-12-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_music_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='category',
            field=models.IntegerField(default=1),
        ),
    ]
