# Generated by Django 2.1.3 on 2018-12-09 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_music_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='album_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='music_cover',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='music',
            name='music_path',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
