# Generated by Django 2.1.3 on 2018-12-09 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20181209_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='album_name',
            new_name='album',
        ),
        migrations.AddField(
            model_name='music',
            name='artist',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
