# Generated by Django 2.1.3 on 2018-12-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20181209_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='music_cover',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='music_path',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
