# Generated by Django 2.1.3 on 2018-12-09 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20181209_1856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='music_path',
            new_name='url',
        ),
    ]
